---
- name: Create a Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: "nginx-deployment"
        namespace: "{{ project_name }}"
      spec:
        selector:
          matchLabels:
            app: "nginx"
        replicas: 1
        template:
          metadata:
            namespace: "{{ project_name }}"
            labels:
              app: "nginx"
          spec:
            containers:
              - name: nginx
                image: nginx:1.24.0
                ports:
                  - containerPort: 80
- name: Create a Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "nginx-service"
        namespace: "{{ project_name }}"
      spec:
        type: LoadBalancer
        selector:
          app: "nginx"
        ports:
          - port: 8080
            targetPort: 80
            protocol: TCP
